/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "date": Date;
    }
    interface MyUnrelatedComponent {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyUnrelatedComponentElement extends Components.MyUnrelatedComponent, HTMLStencilElement {
    }
    var HTMLMyUnrelatedComponentElement: {
        prototype: HTMLMyUnrelatedComponentElement;
        new (): HTMLMyUnrelatedComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-unrelated-component": HTMLMyUnrelatedComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "date"?: Date;
    }
    interface MyUnrelatedComponent {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-unrelated-component": MyUnrelatedComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-unrelated-component": LocalJSX.MyUnrelatedComponent & JSXBase.HTMLAttributes<HTMLMyUnrelatedComponentElement>;
        }
    }
}
